name: 发布

on:
  workflow_dispatch:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: false
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:

      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: 设置yarn的network-timeout
        run: yarn config set network-timeout 1000000

      - name: 安装lerna
        run: |
              yarn global add lerna
              echo "$(yarn global bin)" >> $GITHUB_PATH

      - name: 安装依赖2
        run: lerna bootstrap

      - name: build
        run: yarn prepare

